In [1]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB, quicksum

from constants import (
    MAX_TAXI_ZONE_ID,
    location_ids,
    excluded_location_ids,
    location_id_to_index,
    num_locations,
    taxi_type,
    YEARS,
    MONTHS
)

$$\begin{align*}
\max_{\bar{e}, \bar{f}, \bar{a}} \quad & \frac{1}{K\Delta} \sum_{k=0}^{K-1} \sum_{i=1}^r \sum_{j=1}^r \bar{a}_i \lambda_i(t + k\Delta) P_{ij}(t + k\Delta) c_{ij}(t + k\Delta) \cdot\Delta \\
\text{subject to} \quad 

& \frac{1}{K\Delta} \sum_{k=0}^{K-1} \lambda_i(t + k\Delta) P_{ij}(t + k\Delta) \bar{a}_i \cdot \Delta  = \frac{1}{K\Delta} \sum_{k=0}^{K-1} \mu_{ij}(t + k\Delta) \bar{f}_{ij} \cdot \Delta \\

& \frac{1}{K\Delta} \left(\sum_{k=0}^{K-1} \mu_{ij}(t + k\Delta) \cdot \Delta\right) \bar{e}_{ij} \leq \sum_{j=1}^r \left(\frac{1}{K\Delta} \sum_{k=0}^{K-1} \mu_{ji}(t + k\Delta)  \cdot \Delta \right)\bar{f}_{ji}\\

& \sum_{\substack{j=1 \\ j \neq i}}^r \frac{1}{K\Delta} \left(\sum_{k=0}^{K-1} \mu_{ji}(t + k\Delta) \cdot \Delta\right) \bar{e}_{ji} \leq \frac{1}{K\Delta}\left(\sum_{k=0}^{K-1} \lambda_i(t + k\Delta)\cdot \Delta \right) \bar{a}_i \\

& \frac{1}{K\Delta} \left(\sum_{k=0}^{K-1} \lambda_i(t + k\Delta)\cdot \Delta \right) \bar{a}_i  \\

&\quad\leq \sum_{\substack{j=1 \\ j \neq i}}^r \left(\frac{1}{K\Delta} \sum_{k=0}^{K-1} \mu_{ji}(t + k\Delta)  \cdot \Delta \right)\bar{e}_{ji} + \sum_{j=1}^r \left(\frac{1}{K\Delta} \sum_{k=0}^{K-1} \mu_{ji}(t + k\Delta) \cdot \Delta \right)\bar{f}_{ji} \\

& \frac{1}{K\Delta} \left(\sum_{k=0}^{K-1} \lambda_i(t + k\Delta)\cdot \Delta \right) \bar{a}_i + \sum_{\substack{j=1 \\ j \neq i}}^r \left(\frac{1}{K\Delta} \sum_{k=0}^{K-1} \mu_{ij}(t + k\Delta)  \cdot \Delta \right)\bar{e}_{ij} \\

&\quad = \sum_{\substack{j=1 \\ j \neq i}}^r \left(\frac{1}{K\Delta} \sum_{k=0}^{K-1} \mu_{ji}(t + k\Delta)  \cdot \Delta \right)\bar{e}_{ji} + \sum_{j=1}^r \left(\frac{1}{K\Delta} \sum_{k=0}^{K-1} \mu_{ji}(t + k\Delta) \cdot \Delta \right)\bar{f}_{ji} \\
& e_{ij}, f_{ij} \in [0, 1], \sum_{i=1}^r \sum_{j=1}^r e_{ij} + f_{ij} = 1\\
& 0 \leq \bar{a}_i \leq 1
\end{align*}
$$

In [2]:
Delta = 20 # in minutes
T_max = int(24 * (60 // Delta))

In [3]:
with np.load('trip_counts.npz') as data:
    trip_counts = data['trip_counts']
    num_dates = data['num_dates']

with np.load('mu.npz') as data:
    mu = data['mu']
    
lambda_ = trip_counts.sum(axis=2) / (Delta / 60 * num_dates)

P = trip_counts / trip_counts.sum(axis=2, keepdims=True)

In [4]:
mu_masked = np.nan_to_num(mu, nan=0.0)

In [5]:
def compute_time_averaged(lambda_, mu, t_start, K, T_max):
    time_indices = [(t_start + k) % T_max for k in range(K)]
    lambda_avg = np.mean(lambda_[time_indices, :], axis=0)         # shape: (r,)
    mu_avg = np.mean(mu[time_indices, :, :], axis=0)               # shape: (r, r)
    return lambda_avg, mu_avg


In [6]:
def solve_routing(lambda_, mu, P, Delta, t_start=0, K=6):
    lambda_avg, mu_avg = compute_time_averaged(lambda_, mu, t_start, K, T_max)
    P_avg = np.mean(P[[(t_start + k) % T_max for k in range(K)], :, :], axis=0)  # optional if P is time-varying

    r = lambda_.shape[1]
    model = gp.Model("lookahead_empty_car_routing")
    model.Params.LogToConsole = 1
    
    # Variables
    a = model.addVars(r, lb=0, ub=1, name="a")
    e = model.addVars(r, r, lb=0, ub=1, name="e")
    f = model.addVars(r, r, lb=0, ub=1, name="f")

    # Objective
    model.setObjective(
        quicksum(a[i] * lambda_avg[i] * P_avg[i, j] for i in range(r) for j in range(r)),
        GRB.MAXIMIZE
    )

    # Eq. 10a: Ride flow balance
    ride_flow_expr = {
        (i, j): a[i] * lambda_avg[i] * P_avg[i, j] - mu_avg[i, j] * f[i, j]
        for i in range(r) for j in range(r)
    }
    model.addConstrs((ride_flow_expr[i, j] == 0 for i in range(r) for j in range(r)), name="ride_flow_balance")

    # Eq. 10b: Empty car flow balance
    model.addConstrs((
        mu_avg[i, j] * e[i, j] <= quicksum(mu_avg[l, i] * f[l, i] for l in range(r))
        for i in range(r) for j in range(r) if i != j
    ), name="empty_car_flow")

    # Eq. 10c: Supply conservation (lower bound)
    model.addConstrs((
        quicksum(mu_avg[j, i] * e[j, i] for j in range(r) if j != i) <= lambda_avg[i] * a[i]
        for i in range(r)
    ), name="supply_lower")
    
    # Eq. 10c: Supply conservation (upper bound)
    model.addConstrs((
        lambda_avg[i] * a[i] <=
        quicksum(mu_avg[j, i] * e[j, i] for j in range(r) if j != i) +
        quicksum(mu_avg[j, i] * f[j, i] for j in range(r))
        for i in range(r)
    ), name="supply_upper")
    
    # Eq. 10d: Car flow balance
    model.addConstrs((
        lambda_avg[i] * a[i] +
        quicksum(mu_avg[i, j] * e[i, j] for j in range(r) if j != i)
        ==
        quicksum(mu_avg[j, i] * e[j, i] for j in range(r) if j != i) +
        quicksum(mu_avg[j, i] * f[j, i] for j in range(r))
        for i in range(r)
    ), name="car_flow_balance")
    

    # Unit mass constraint
    model.addConstr(
        quicksum(e[i,j] + f[i,j] for i in range(r) for j in range(r)) == 1,
        name="unit_mass"
    )
    
    model.optimize()
    
    return model, a, e, f, lambda_avg, mu_avg


In [7]:
t_start = 24
K = 4

res = solve_routing(lambda_, mu_masked, P, Delta, t_start=t_start, K=K)
model, a, e, f, lambda_avg, mu_avg = res

Set parameter Username
Set parameter LicenseID to value 2651514
Academic license - for non-commercial use only - expires 2026-04-14
Set parameter LogToConsole to value 1
Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (mac64[arm] - Darwin 24.1.0 24B2083)

CPU model: Apple M4 Pro
Thread count: 14 physical cores, 14 logical processors, using up to 14 threads

Optimize a model with 110921 rows, 110685 columns and 12790692 nonzeros
Model fingerprint: 0xb7100257
Coefficient statistics:
  Matrix range     [9e-06, 4e+02]
  Objective range  [6e-01, 4e+02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 29765 rows and 30000 columns (presolve time = 9s)...
Presolve removed 39765 rows and 40000 columns (presolve time = 19s)...
Presolve removed 49765 rows and 50000 columns (presolve time = 32s)...
Presolve removed 58266 rows and 58501 columns (presolve time = 49s)...
Presolve removed 58266 rows and 58501 columns (presolve time = 51s)...
Presolve removed 58266 

In [8]:
# # convert e, f, and a to numpy arrays

# e_np = np.zeros((num_locations, num_locations))
# f_np = np.zeros((num_locations, num_locations))
# a_np = np.zeros(num_locations)

# for i in range(num_locations):
#     for j in range(num_locations):
#         e_np[i, j] = e[i, j].X
#         f_np[i, j] = f[i, j].X
#     a_np[i] = a[i].X

In [9]:
r = len(location_ids)

def compute_q_matrix(a, e, f, mu_avg, lambda_avg):
    """
    a, e, f: dicts of Gurobi variable values: a[i], e[i,j], f[i,j]
    mu_avg: 2D array of shape (r, r) averaged over time
    lambda_avg: 1D array of shape (r,) averaged over time
    """
    r = len(a)
    q = np.zeros((r, r))

    # Precompute denominator for qij and qii
    for i in range(r):
        denom = sum(mu_avg[k, i] * f[k, i].X for k in range(r))

        for j in range(r):
            if i != j:
                if denom > 0:
                    q[i, j] = mu_avg[i, j] * e[i, j].X / denom
                else:
                    print(f"Denominator is zero for i={i}, j={j}. Setting q[{i}, {j}] to 0.")
                    q[i, j] = 0.0
            else:
                # qii computation
                numerator = lambda_avg[i] * a[i].X - sum(
                    mu_avg[k, i] * e[k, i].X for k in range(r) if k != i
                )
                q[i, i] = numerator / denom if denom > 0 else 0.0

    return q

In [10]:
Q = compute_q_matrix(a, e, f, mu_avg, lambda_avg)

In [11]:
Q

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

Rows of Q should sum to 1, by the constraint 10.d.

In [12]:
notsumtoone = np.argwhere(~np.isclose(Q.sum(axis=1), 1.0)).flatten()
print(notsumtoone)
print(Q[notsumtoone].sum(axis=1))

[ 21  97 172]
[2.         0.         1.00502866]


There seems to be some unknown numerical/logical issue.